// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WargameData;

#nullable disable

namespace WargameData.Migrations
{
    [DbContext(typeof(WargameDbContext))]
    [Migration("20260327004353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WargameVisualizer.Protos.Scenario", b =>
                {
                    b.Property<string>("ScenarioId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("ScenarioId");

                    b.ToTable("Scenarios", (string)null);
                });

            modelBuilder.Entity("WargameVisualizer.Protos.Scenario", b =>
                {
                    b.OwnsOne("WargameVisualizer.Protos.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<string>("ScenarioId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("MaxLatitude")
                                .HasColumnType("float")
                                .HasColumnName("BoundingBox_MaxLatitude");

                            b1.Property<double>("MaxLongitude")
                                .HasColumnType("float")
                                .HasColumnName("BoundingBox_MaxLongitude");

                            b1.Property<double>("MinLatitude")
                                .HasColumnType("float")
                                .HasColumnName("BoundingBox_MinLatitude");

                            b1.Property<double>("MinLongitude")
                                .HasColumnType("float")
                                .HasColumnName("BoundingBox_MinLongitude");

                            b1.HasKey("ScenarioId");

                            b1.ToTable("Scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioId");
                        });

                    b.Navigation("BoundingBox");
                });
#pragma warning restore 612, 618
        }
    }
}
