{{- if .Values.workloadIdentity.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "war-game-visualizer.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
{{- end }}
